### PR TITLE
Added a Package manifest for Swift 5.3 to resolve the Xcode 12 warning

### PR DESCRIPTION
**Pull request by asolovev**
Adding this library into Swift Package Manager using Xcode 12 generates a following warning
"The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99."
There are a couple solutions to this that I know:

1. Deployment target can be increased to .iOS(.v9) in the main Package.swift file.

1. A separate Package manifest can be created to target a specific swift version.

I went the second way to make changes smaller.

### CODE REVIEW

**Comment by InderKumarRathore** [comment]
Thanks for taking time to raise the pull request. I was thinking not to support iOS 8 as cocoapods was also throwing me warning. Would prefer to remove the support for iOS 8, instead of maintaining a new file. Also I checked the supported device for iOS 8 and iOS 9, both are same (supporting from iPhone 4s).

**Comment by asolovev** [comment]
Sounds good as well. Do you want me to update this PR to be a small change in the original Package.swift? It should resolve this warning with SwiftPM without requiring any adjustments for other dependency managers for now.

**Comment by InderKumarRathore** [comment]
Up to you. If you don't I'll do it tomorrow

**Comment by asolovev** [comment]
Thank you. I have updated this PR to change the main Package.swift as you suggested. If you will do a bigger PR soon, you can skip this one and apply this change yourself along with others. It is a one-liner anyway :)

**Pull request merged**
